package com.afyaquik.doctor.enums;

public enum ObservationType {
    SYSTEMIC, PHYSICAL, CHIEF_COMPLAINT, HISTORY_OF_PRESENT_ILLNESS, EXAMINATION, DIAGNOSIS, PRESCRIPTION, LABORATORY, RADIOLOGY, OTHER
}
