spring:
  web:
    resources:
      static-locations: classpath:/static/,file:./src/main/resources/static/
  datasource:
    url: jdbc:postgresql://localhost:5433/afyaquik #TODo: store in env
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: false

  jpa:

    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org.springframework: TRACE
