spring:
  web:
    resources:
      static-locations: classpath:/static/,file:./src/main/resources/static/
  datasource:
    url: jdbc:postgresql://localhost:5433/afyaquik #TODo: store in env
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: false

  jpa:

    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
app:
  cookie:
    secure: false  # HTTP in dev; set true in production (HTTPS required)
  jwt:
    secret: ${APP_JWT_SECRET:?agdasfghjklqwertyuiopzxcvbnm1234567890} # Set a random JWT signing secret of at least 32 bytes
  bootstrap:
    password: ${APP_BOOTSTRAP_PASSWORD:?jklqwertyuiopzxcvbnm1234567890} # Set a random bootstrap password of at least 32 bytes
logging:
  level:
    root: INFO
    com.afyaquik: DEBUG
